export { default as authApi } from "./authApi.js";
export { default as serviceApi } from "./serviceApi.js";
export { default as userApi } from "./userApi.js";
export { default as clinicApi } from "./clinicApi.js";
export { default as uploadApi } from "./uploadApi.js";
export { default as specialtyApi } from "./specialtyApi.js";
export { default as workApi } from "./workApi.js";
export { default as scheduleApi } from "./scheduleApi.js";
export { default as bookingApi } from "./bookingApi.js";
